version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./app.db
      - SECRET_KEY=${SECRET_KEY:-your-secure-secret-key-needs-to-be-changed-in-production}
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440
      - CORS_ORIGINS=http://localhost:8080,http://frontend:80
      - REDIS_URL=redis://redis:6379/0
      - CACHE_ENABLED=true
      - CACHE_TTL=3600
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    restart: unless-stopped
    networks:
      - workshop-network
    depends_on:
      - redis
      - ollama

  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=http://localhost:8000
    restart: unless-stopped
    networks:
      - workshop-network
    depends_on:
      - backend

  # Redis service for caching
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped
    networks:
      - workshop-network

  # Ollama service
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    networks:
      - workshop-network

networks:
  workshop-network:
    driver: bridge

volumes:
  backend_data:
  redis_data:
  ollama_data:
